export const SET_CURRENT_POSITION_USER = 'SET_CURRENT_POSITION_USER';
export const READ_COORDINATE_SELLER = 'READ_COORDINATE_SELLER';
export const SEARCH = 'SEARCH';
export const LOADING_READ_USER = 'LOADING_READ_USER';
export const SET_TOKEN = 'SET_TOKEN';